# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
	obj = bld.create_ns3_program('minuet-scenario', ['minuet'])
	obj.source = 'minuet-scenario.cc'
	
	obj = bld.create_ns3_program('minuet-example-wave', ['minuet'])
	obj.source = 'minuet-example-wave.cc'